spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3309}/${DB_NAME:test}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:monMotDePasseSuperSecret}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8085

omdb.api-key=ab5f54b5
omdb.base-url=https://www.omdbapi.com/

# Configuration OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# JWT
security.jwt.secret=CHANGE_ME_TO_A_LONG_RANDOM_SECRET_KEY_32CHARS_MIN
security.jwt.expiration=3h

# Synchronisation APIs externes
sync.artist.url=http://localhost:8083/api/artistes
sync.poster.url=http://localhost:8081/api/posters
